[package]
name = "overlay-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
csv.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
prost = "0.14"
telemetry-parser = { git = "https://github.com/AdrianEddy/telemetry-parser.git", rev = "c0110c546e1fdc30014e6556ff49d81c4ca94821" }

[dev-dependencies]
tempfile.workspace = true
